# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Cuatrovientos\ArteanBundle\Entity\User: 
            algorithm: md5
            encode_as_base64: false
            iterations: 0
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]        
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        
        artean_db_provider:
            entity:
                class: CuatrovientosArteanBundle:User
                property: login
                # if you're using multiple entity managers
                # manager_name: customer
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:            
            anonymous: ~

            pattern:    ^/
            context: session_key
            form_login:
                provider: artean_db_provider
                login_path: /login
                check_path: /login_check
                username_parameter: _username
                password_parameter: _password
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
                #target_path_parameter: /admin/chatgroup
            logout:
                path:   /logout
                target: /login


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/artean/admin/offer, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/artean/admin/user/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/artean/admin, roles: ROLE_ADMIN }
#        - { path: ^/artean/user, roles: ROLE_USER }

