# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension.color:
        class: Cuatrovientos\ArteanBundle\Twig\JobRequestStatusColorExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.flag:
        class: Cuatrovientos\ArteanBundle\Twig\CountryFlagExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.extract:
        class: Cuatrovientos\ArteanBundle\Twig\ExtractExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.pagecolor:
        class: Cuatrovientos\ArteanBundle\Twig\PageStatusColorExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.degree:
        class: Cuatrovientos\ArteanBundle\Twig\DegreeIconExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.mail:
        class: Cuatrovientos\ArteanBundle\Twig\MailStatusExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_extension.mailing:
        class: Cuatrovientos\ArteanBundle\Twig\MailingStatusExtension
        public: false
        tags:
            - { name: twig.extension }